use linguasteg_core::{CoreResult, RealizationPlan};

/// Italian scaffold module generated by `cargo xtask add-lang`.
///
/// TODO:
/// - replace type aliases with native language pack implementation
/// - provide native templates, symbolic schemas, and parser
/// - update runtime registry in `linguasteg-cli/src/app/runtime.rs`
pub type ItalianPrototypeLanguagePack = crate::en::EnglishPrototypeLanguagePack;
pub type ItalianPrototypeConstraintChecker = crate::en::EnglishPrototypeConstraintChecker;
pub type ItalianPrototypeRealizer = crate::en::EnglishPrototypeRealizer;
pub type ItalianPrototypeSymbolicMapper = crate::en::EnglishPrototypeSymbolicMapper;

pub fn parse_italian_prototype_text(stego_text: &str) -> CoreResult<Vec<RealizationPlan>> {
    crate::en::parse_english_prototype_text(stego_text)
}

#[cfg(test)]
mod tests {
    use super::parse_italian_prototype_text;

    #[test]
    fn parser_scaffold_delegates_to_english_prototype() {
        let text = "the manager labels clear report. the architect in winter at the office, records manual.";
        let plans = parse_italian_prototype_text(text)
            .expect("scaffold parser should delegate successfully");
        assert_eq!(plans.len(), 2);
    }
}
